tasks:
  - name: player-service-backend
    before: |
      sdk install java 17.0.3-ms
      \
      sdk default java 17.0.3-ms
    init: |
      cd players-backend-java
      mvn package -DskipTests
  - name: player-service-fe
    init: |
      cd players-ui-react
      yarn install

ports:
  - port: 8080  # Port for player-service-app
    onOpen: open-preview
  - port: 3000  # Port for player-service-fe
    onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot